#!/bin/sh
## muss command-line music player interface
# Dan Brown, 2010
# 
# example quicksearch usage: muss beatl pepp
#                            muss elvis not presl
#
# interactive search usage:  muss
# note: interactive mode depends on dmenu with
#       patches for xmms style multiple search
#       and filtermode and xft support.
#

DEBUG=0
PLMARKER="__playlist__ " 

if [ -f $HOME/.dmenurc ]
then
  . $HOME/.dmenurc
else
  DMENU='dmenu'
fi
DMENU="$DMENU -i -l 10 -f -xs"

PLAYLISTS=`mpc lsplaylists | sed -e "s/.*/$PLMARKER&/"`
[ $DEBUG -gt 1 ] && echo "playlists: $PLAYLISTS"
FILES=`mpc listall`
[ $DEBUG -gt 1 ] && echo "files (head):" `echo "$FILES" | head`

if [ $# -gt 0 ]
then
  # quicksearch mode
  # use the command line parameters as search terms
  # matching is done by (full) filepath
  # supports the "not" keyword to exclude patterns
  CRITERIA=`echo $* | sed \
    -e 's/not \(\S\)/__-v__\1/Ig' \
    -e 's/\S*/| grep -i &/g' \
    -e 's/__-v__/-v /g'`
  [ $DEBUG -gt 1 ] && echo "criteria = $CRITERIA"
  ALLMATCHES=`eval "echo \"$FILES\\n$PLAYLISTS\" $CRITERIA"`
else
  # interactive browse/search mode
  ALLMATCHES=`echo "$FILES\\n$PLAYLISTS" | $DMENU`
fi

[ $DEBUG -gt 1 ] && echo "all matches = $ALLMATCHES ."

LOADCOMMANDS=`echo "$ALLMATCHES" | sed \
  -e '/^$/d' \
  -e 's/.*/mpc add \"&\"/g' \
  -e "s/mpc add \"$PLMARKER/mpc load \"/g"`
[ $DEBUG -gt 0 ] && echo "load commands: $LOADCOMMANDS"

# check to see if we found no music and should do nothing
[ `echo "$LOADCOMMANDS" | wc -c` -eq 1 ] && exit

mpc clear > /dev/null
echo "$LOADCOMMANDS" | while read LOADCOMMAND 
do
  eval $LOADCOMMAND > /dev/null
done
mpc play > /dev/null

