#!/bin/sh
## muss command-line music player interface
# Dan Brown, 2010
# 
# note: interactive mode depends on dmenu with
#       patches for xmms style multiple search
#       and filtermode multiple output.

HELP_MESSAGE="muss version 0.1
usage:   \"muss [options] [[not] <keyword>]...\" 
example: \"muss elvis\"
         \"muss elv pres not jailhouse\"
         \"muss lion rich -a -r\"
         \"muss\" (opens an interactive search menu)
         \"muss -p -l\"
         \"muss -n\"
options:
 -h help (also recognizes -? --help)
 -a append to (don't clear) existing playlist
 -q quiet. disables autoplay for the new playlist
 -r randomize playlist order for the new playlist
 -l list items in current playlist (don't browse)
 -p play/pause current playlist (don't browse)
 -s stop current playlist (don't browse)
 -n next song in current playlist (don't browse)
 -b back to previous song in current playlist (don't browse)
"

DEBUG=0
PLMARKER="__playlist__ " 

# print help message and usage, then exit
echo " $* " | grep -i -E '[ \t]\-{1,2}(help|h|\?)[ \t]' > /dev/null && \
  echo "$HELP_MESSAGE" && exit

if [ -f $HOME/.dmenurc ]
then
  . $HOME/.dmenurc
else
  DMENU='dmenu'
fi
DMENU="$DMENU -i -l 10 -f -xs"

# parse arguments for recognized options
# all non-help (non-early-termination) arguments should be listed below
IGNOREARGS='-a -q -r -l -p -s -n -b'
NOBROWSEARGS='-l -p -s -n -b'
IGNOREFILTER=" "`echo "$IGNOREARGS" | sed -e 's/ -/ \\\\| -/g'`" "
NOBROWSEFILTER=" "`echo "$NOBROWSEARGS" | sed -e 's/ -/ \\\\| -/g'`" "
SEARCHTERMS=`echo " $* " | sed \
  -e 's/ /  /g' \
  -e "s/$IGNOREFILTER/ /Ig"`
[ $DEBUG -gt 1 ] && echo "search terms: $SEARCHTERMS ."

collect_items() {
  PLAYLISTS=`mpc lsplaylists | sed -e "s/.*/$PLMARKER&/"`
  [ $DEBUG -gt 1 ] && echo "playlists: $PLAYLISTS"
  FILES=`mpc listall`
  [ $DEBUG -gt 1 ] && echo "files (head):" `echo "$FILES" | head`
}

if [ `echo $SEARCHTERMS | wc -w` -gt 0 ]
then
  # quicksearch mode
  # use the command line parameters as search terms
  # matching is done by (full) filepath
  # supports the "not" keyword to exclude patterns
  CRITERIA=`echo $SEARCHTERMS | sed \
    -e 's/not \(\S\)/__-v__\1/Ig' \
    -e 's/\S*/| grep -i \"&\"/g' \
    -e 's/\"__-v__/-v \"/g' \
    -e 's/ \"-/ \"\\\\-/g'`
  [ $DEBUG -gt 1 ] && echo "criteria = $CRITERIA"
  collect_items
  ALLMATCHES=`eval "echo \"$FILES\\n$PLAYLISTS\" $CRITERIA"`
elif [ `echo " $* " | grep -i "$NOBROWSEFILTER" | wc -l` -gt 0  ]
then
  # we won't look for music to add.
  # we are probably just adjusting mpc state
  ALLMATCHES=""
else
  # interactive browse/search mode
  collect_items
  ALLMATCHES=`echo "$FILES\\n$PLAYLISTS" | $DMENU`
fi

[ $DEBUG -gt 1 ] && echo "all matches: $ALLMATCHES ."

LOADCOMMANDS=`echo "$ALLMATCHES" | sed \
  -e '/^$/d' \
  -e 's/.*/mpc add \"&\" > \/dev\/null;/g' \
  -e "s/mpc add \"$PLMARKER/mpc load \"/g"`
[ $DEBUG -gt 0 ] && echo "load commands: $LOADCOMMANDS ."

# check to see if we found some music to load
if [ `echo "$LOADCOMMANDS" | wc -c` -ge 5 ]
then
  # clear playlist unless in append mode
  echo " $* " | grep -i -E ' -a ' > /dev/null
  [ $? -eq 0 ] || mpc clear > /dev/null

  eval "$LOADCOMMANDS > /dev/null"

  # randomize playlist
  # note this should be done before autoplay happens
  echo " $* " | grep -i -E ' -r ' > /dev/null
  [ $? -eq 0 ] && mpc shuffle > /dev/null

  # start autoplay unless we've been asked to stay quiet
  echo " $* " | grep -i -E ' -q ' > /dev/null
  [ $? -eq 0 ] || mpc play > /dev/null
fi

# randomize playlist
# TODO: come up with a new approach that doesn't do this twice
echo " $* " | grep -i -E ' -r ' > /dev/null
[ $? -eq 0 ] && mpc shuffle > /dev/null

# advance to next item in playlist
echo " $* " | grep -i -E ' -n ' > /dev/null
[ $? -eq 0 ] && mpc next > /dev/null

# back to previous item in playlist
echo " $* " | grep -i -E ' -b ' > /dev/null
[ $? -eq 0 ] && mpc prev > /dev/null

# toggle play/pause
echo " $* " | grep -i -E ' -p ' > /dev/null
[ $? -eq 0 ] && mpc toggle > /dev/null

# stop playing
echo " $* " | grep -i -E ' -s ' > /dev/null
[ $? -eq 0 ] && mpc stop > /dev/null

# list playlist
echo " $* " | grep -i -E ' -l ' > /dev/null
[ $? -eq 0 ] && mpc playlist

